### ISSUE TITLE
System limit for number of file watchers reached

### ISSUE THREAD

**Issue by IvanTurgenev** [silverwind/droppy#431]
I have like 200 gb of multiple types of data droppy doesnt like it.

several lines of

```
droppy    |     at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
droppy    |     at Object.watch (fs.js:1474:34)
droppy    |     at createFsWatchInstance (/droppy/node_modules/chokidar/lib/nodefs-handler.js:119:15)
droppy    |     at setFsWatchListener (/droppy/node_modules/chokidar/lib/nodefs-handler.js:166:15)
droppy    |     at NodeFsHandler._watchWithNodeFs (/droppy/node_modules/chokidar/lib/nodefs-handler.js:331:14)
droppy    |     at NodeFsHandler._handleFile (/droppy/node_modules/chokidar/lib/nodefs-handler.js:395:23)
droppy    |     at NodeFsHandler._addToNodeFs (/droppy/node_modules/chokidar/lib/nodefs-handler.js:628:21)
droppy    | 2020-08-23 03:46:00 [ERROR] ENOSPC: System limit for number of file watchers reached, watch file path xxxx

```
compose file

```
version: '2'
services:
  droppy:
    container_name: droppy
    image: silverwind/droppy
    network_mode: host
    volumes:
      - ./config:/config
      - /data/sambapriv:/files
    restart: unless-stopped
```
